# Uncomment the next line to define a global platform for your project
# platform :ios, '15.2'

target 'TinderClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinderClone
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'SDWebImage'
  pod 'JGProgressHUD'

end
